#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-a"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e9b4fbab53204d73a3c7726d40839ee1" }
]

[assets]
directory = "./public"
